name: Coveralls cubrimiento

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:

    runs-on: ubuntu-latest

    steps:
    - name: Clonando repositorio
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install ./server
    - run: npm install
    - run: sudo systemctl start mongod
    - run: npm run test:cov
    - name: Accion de coveralls 
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      